services:
  db:
    image: postgres:17-alpine
    container_name: postgres17_alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: mydatabase
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  db_data: {}
