spring:
  application:
    name: demo
  datasource:
    password: ${database.password}
    url: ${database.jdbc.url}
    username: ${database.password}
  flyway:
    enabled: true
    schemas: public
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
